name: dartmark
description: A sample command-line application.
version: 1.0.0
publish_to: none 

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  zard: ^0.0.23
  tyto: ^0.0.1-dev.6
  acanthis: ^1.4.6
  luthor: ^0.15.0
  ack: ^0.1.2
  yaml: ^3.1.3
  vine: ^1.7.2
  json_schema_builder: ^0.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
