name: dartmark
description: A sample command-line application.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  tyto: ^0.0.1-dev.6
  acanthis: ^1.2.1
  luthor: ^0.6.1
  vine: ^1.5.1
  ack: ^0.1.2
  validart: ^0.1.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
